# Generated by Django 4.2.6 on 2023-10-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MapElenent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(unique=True)),
                ('y', models.IntegerField(unique=True)),
                ('value', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.map')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_max', models.IntegerField(default=150)),
                ('y_max', models.IntegerField(default=150)),
                ('x_min', models.IntegerField(default=50)),
                ('y_min', models.IntegerField(default=50)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mapelenent')),
            ],
        ),
    ]
