# Generated by Django 4.2.6 on 2023-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapelenent',
            old_name='value',
            new_name='height',
        ),
        migrations.AlterField(
            model_name='currentvalues',
            name='x_max',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='currentvalues',
            name='x_min',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='currentvalues',
            name='y_max',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='currentvalues',
            name='y_min',
            field=models.IntegerField(default=100),
        ),
    ]
