# Generated by Django 4.2.6 on 2023-10-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_value_mapelenent_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapelenent',
            name='map',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
