# Generated by Django 4.2.6 on 2023-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_mapelenent_map_delete_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapelenent',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mapelenent',
            name='y',
            field=models.IntegerField(),
        ),
    ]
