# Generated by Django 4.2.6 on 2023-10-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mapelenent_x_alter_mapelenent_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapelenent',
            name='height',
        ),
        migrations.RemoveField(
            model_name='mapelenent',
            name='x',
        ),
        migrations.RemoveField(
            model_name='mapelenent',
            name='y',
        ),
        migrations.AddField(
            model_name='mapelenent',
            name='arr_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapelenent',
            name='x_max',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='mapelenent',
            name='x_min',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mapelenent',
            name='y_max',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='mapelenent',
            name='y_min',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='CurrentValues',
        ),
    ]
