# Generated by Django 4.2.6 on 2023-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_mapelenent_height_remove_mapelenent_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapelenent',
            name='x_max',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='mapelenent',
            name='y_min',
            field=models.IntegerField(default=150),
        ),
    ]
