# Generated by Django 4.2.6 on 2023-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mapelenent_x_max_alter_mapelenent_x_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapelenent',
            name='x_max',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='mapelenent',
            name='x_min',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='mapelenent',
            name='y_max',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='mapelenent',
            name='y_min',
            field=models.IntegerField(default=100),
        ),
    ]
